spring:
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: dev

  output:
    ansi:
      enabled: always

  datasource:
    hikari:
      auto-commit: false

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

springdoc:
  default-produces-media-type: application/json

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.rest1: DEBUG

github:
  api:
    base-url: https://api.github.com/
    token: ${GITHUB_TOKEN}

jwt:
  secret: ${SECRET_KEY}
  access-token-expiration-in-milliseconds: 7200000 # 두 시간

openai:
  api:
    key: ${OPENAI_API_KEY}
