spring:
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # 기본 dev

  output:
    ansi:
      enabled: always

  datasource:
    url: ${DB_URL:jdbc:h2:./db_dev;MODE=MySQL}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true

  mvc:
    hidden method:
      filter:
        enabled: true

springdoc:
  default-produces-media-type: application/json

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.rest1: DEBUG