spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb;MODE=MySQL}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
